apiVersion: v1
kind: Service
metadata:
  name: mlrf-api
  namespace: mlrf
  labels:
    app.kubernetes.io/name: mlrf-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: mlrf
spec:
  type: ClusterIP
  selector:
    app: mlrf-api
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
